### ISSUE TITLE
Améliorer l'ergonomie de la recherche

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#15]
Quelques utilisateurs ont remonté le fait que le fonctionnement actuel du moteur leur paraît contre-intuitif.

**Comment by bzg** [comment]
@garronej est-ce fait ?

**Comment by garronej** [comment]
Non pas encore mais je m'y atelle demain. 👍🏻

**Comment by bzg** [comment]
Merci !

**Comment by garronej** [comment]
I think I'll use https://github.com/nextapps-de/flexsearch, it seems more suited for the usecase than Fzf.  
It's what's in place in https://nextra.site/ and it seem's to be work very well.

**Comment by bzg** [comment]
LGTM

**Comment by garronej** [comment]
I've implemented Flexsearch instead of Fzf.  
The search reasult are much better.  
Had to refactor a lot because Flexsearch works with a service worker (the sorting is made on a different process) so the API is async and can't be within a selector.  
Anyway, I haven't pushed it in prod yet because Flexsearch unlike Flexsearch dosen't provide matches hilight like Fzf does but it's no big deal, I'll just adapt @B2o5T implementation: https://github.com/codegouvfr/nextra-theme-dsfr/blob/main/src/components/highlight-matches.tsx

**Comment by garronej** [comment]
It's done.  
I was in the denyal with Fzf the result are *much better* with flexsearch. There's no arguing it.  

ChatGPT is just too smart, he converted the React code into a vanila function like a boss: https://chat.openai.com/share/4dfcf80c-9ef0-4580-8cac-48235f4c438b
